from django.core.exceptions import ValidationError


def validate_card_number(value):
    def luhn_checksum(card_number):
        def digits_of(n):
            return [int(d) for d in str(n)]

        digits = digits_of(card_number)
        odd_digits = digits[-1::-2]
        even_digits = digits[-2::-2]
        checksum = 0
        checksum += sum(odd_digits)
        for d in even_digits:
            checksum += sum(digits_of(d * 2))
        return checksum

    if luhn_checksum(value) % 10 != 0:
        raise ValidationError("Invalid card number.")
